theme: jekyll-theme-dinky
title: Kevin Xu DATA 410 Project 2
description: An introduction to Locally Weighted Regression and Random Forest Regression, and a comparison of the two using a "Cars" dataset
